//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub chat_id: Uuid,
    pub sender_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub created_at: DateTimeWithTimeZone,
    pub seq: i64,
    #[sea_orm(column_type = "Text")]
    pub message_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub media_url: Option<String>,
    pub media_width: Option<i32>,
    pub media_height: Option<i32>,
    pub media_size_bytes: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub media_content_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chats::Entity",
        from = "Column::ChatId",
        to = "super::chats::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chats,
    #[sea_orm(has_many = "super::message_reads::Entity")]
    MessageReads,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::SenderId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl Related<super::message_reads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageReads.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::message_reads::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::message_reads::Relation::Messages.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
