//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20
#![allow(warnings)]
pub use super::chat_members::Entity as ChatMembers;
pub use super::chats::Entity as Chats;
pub use super::message_reads::Entity as MessageReads;
pub use super::messages::Entity as Messages;
pub use super::users::Entity as Users;
